### ISSUE TITLE
Fix pipeline

### ISSUE THREAD

**Issue by laugmanuel** [theforeman/foreman_omaha#62]
The pipeline is currently broken and reports:
```sh
rake aborted!
NoMethodError: undefined method `configuration_hash' for #<ActiveRecord::DatabaseConfigurations::UrlConfig:0x000055d1bc4ecd50>
/home/runner/work/foreman_omaha/foreman_omaha/vendor/bundle/ruby/2.6.0/gems/dynflow-1.6.6/lib/dynflow/rails/configuration.rb:162:in `default_sequel_adapter_options'
/home/runner/work/foreman_omaha/foreman_omaha/vendor/bundle/ruby/2.6.0/gems/dynflow-1.6.6/lib/dynflow/rails/configuration.rb:202:in `initialize_persistence'
/home/runner/work/foreman_omaha/foreman_omaha/lib/tasks/dynflow.rake:18:in `dynflow_persistence'
/home/runner/work/foreman_omaha/foreman_omaha/lib/tasks/dynflow.rake:23:in `block (2 levels) in <top (required)>'
/home/runner/work/foreman_omaha/foreman_omaha/lib/tasks/dynflow.rake:42:in `block (2 levels) in <top (required)>'
/home/runner/work/foreman_omaha/foreman_omaha/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.6.10/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.6.10/x64/bin/bundle:23:in `<main>'
Tasks: TOP => dynflow:migrate
(See full trace by running task with --trace)
```

It seems to be caused by some external change because the pipeline was green 4 days ago...

**Comment by evgeni** [comment]
@kamils-iRonin fixed all the things in https://github.com/theforeman/foreman_omaha/pull/65

Closing
